docs_dir: 'source'
site_dir: 'docs'
site_name: O Guia do Steam Deck 
#site_url: https://guiadosteamdeck.com.br/

# Theme options: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes
  # bootstrap4 - https://github.com/byrnereese/mkdocs-bootstrap4
  # readthedocs
  # material - https://github.com/squidfunk/mkdocs-material
  # bootstrap386 - https://gitlab.com/lramage/mkdocs-bootstrap386
  # gitbook - https://gitlab.com/lramage/mkdocs-gitbook-theme
# site_dir: ""
site_description: ""
site_author: ""
copyright: >
  Copyright &copy; 2023 - Guia do Steam Deck por Valdecir Carvalho.
  <a href="#__consent"></a>

#repo_url: https://github.com/valdecircarvalho/guia-do-steam-deck/
#repo_name: o guia do steam deck




# use_directory_urls: true

extra_css:
  - stylesheets/extra.css
  
## Plugins Configuration
plugins:
  - open-in-new-tab ## pip install mkdocs-open-in-new-tab
  - awesome-pages ## pip install mkdocs-awesome-pages-plugin - https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin
  - search:
      indexing: 'full'
      lang: pt
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

  - tags:
      enable: true
      tags_file: tags.md
      tags_slugify: headerid.slugify
      tags_slugify_separator: "-"
#  - social:
#      cards_color:
#        fill: "#0FF1CE" 
#        text: "#FFFFFF"




#extensions - https://facelessuser.github.io/pymdown-extensions/ // https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/
markdown_extensions:
  - smarty
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
       kwds:
        case: lower
  - tables
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.critic
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: valdecircarvalho
      repo: guia-do-steam-deck


## material theme config
theme:
  name: material
  #locale: pt
  docs_dir: 'source'
  site_dir: 'docs'
  language: pt-BR 
  include_sidebar: true
  font: false
  logo: /img/guia-do-steam-deck-logo.png
  favicon: /img/favicon.ico
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/lightbulb
        name: Modo Escuro
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/lightbulb-outline
        name: Modo Claro
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs # habilitar depois de organizar
    - navigation.tabs.sticky  
    - #navigation.sections #deixar desabilitado - Mostra os menus fechado e a setinha para abrir o sub-menu
    - #navigation.expand # Inicia com o menu fechado
    - navigation.indexes
    - toc.follow
    - #toc.integrate  # deixa o TOC/Indice do lado direito
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - announce.dismiss
    - navigation.footer
 #Theme icons            
  icon:
    tag:
#      steamdeck: fontawesome/brands/html5
#      emulacao: fontawesome/brands/css3 
#      default: fontawesome/tag
    repo: fontawesome/brands/github
# Extra Session
extra:
  consent:
    title: Cookie consent
    description: >- 
       Usamos cookies para reconhecer suas visitas repetidas e preferências, bem como
       para medir a eficácia de nossa documentação e se os usuários
       encontrar o que eles estão procurando. Com o seu consentimento, você está nos ajudando a
       tornar nossa documentação melhor
    actions:
      - accept
      - reject
  tags:
    HTML5: html
    JavaScript: js
    CSS: css

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/valdecircarvalho
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/guiadosteamdeck


# Navigation Menu

nav:
  - Home: 
    - index.md
    - Steam Deck: 
      - O Steam Deck: steamdeck/steamdeck.md
      - Acessórios: steamdeck/steamdeck-acessorios.md
      - Links Úteis: steamdeck/links.md
    - Configurações Básicas: 
      - Configurações Iniciais: configuracoes/configuracao.md
      - Conta Steam: configuracoes/conta-steam.md
      - Controles: configuracoes/controles.md
      - Teclas de Atalho: configuracoes/teclas-de-atalho-no-steam-deck.md
    - Configurações Avançadas: 
      - Configurações Avançadas: configuracoes-avancadas/configuracoes-avancadas-steam-deck.md
      - Configurações de Performance: configuracoes-avancadas/steamdeck-performance.md          
    - Jogos: 
      - Jogos no Steam Deck: jogos/jogos.md
      - Onde comprar Jogos para o Steam Deck: jogos/onde-comprar-jogos-para-o-steam-deck.md
      - O ProtomDB: jogos/protondb.md 
      - Como rodar jogos não Steam no Steam Deck:
        - Jogos Epic & GoG: jogos/jogos-epic.md
        - Jogos Battle.net: jogos/jogos-battle-net.md
        - Jogos Amazon Prime: jogos/jogos-amazon-prime.md
        - Jogos Xbox e PC Game Pass: jogos/jogos-xbox-pc-game-pass.md
      - Como rodar jogos alternativos no Steam Deck: jogos/jogos-alternativos-steam-deck.md
    - Emulacao: 
      - Emulacao no Steam Deck: emulacao/emulacao.md 
      - Emudeck: emulacao/emudeck.md 
      - Guia Descomplicado do Emudeck: emulacao/guia1.md
      - Guia de Emulação para o Steam Deck - Retro Game Corps: emulacao/retrogamecorps.md
      - Packs de Emuladores para o Steam Deck: emulacao/packs-completos-de-emuladores-para-o-steam-deck.md
      - Retrodeck: emulacao/retrodeck.md
      - Batocera: emulacao/batocera.md
      - Roms: emulacao/roms.md
      - Emulacao - Nintendo:
        - Nintendo Switch: emulacao/nintendo/emulacao-nintendo-switch-steam-deck.md
        - Nintendo Wii U: emulacao/nintendo/emulacao-nintendo-wii-u-steam-deck.md
        - Nintendo Wii: emulacao/nintendo/emulacao-nintendo-wii-steam-deck.md
        - Nintendo 3DS: emulacao/nintendo/emulacao-nintendo-3ds-steam-deck.md        
      - Emulacao - Microsoft:
        - Microsoft Xbox: emulacao/microsoft/microsoft-xbox.md
        - Microsoft Xbox 360: emulacao/microsoft/microsoft-xbox-360.md
      - Emulacao - Sony: 
        - Sony PlayStation 1: emulacao/sony/sony-playstation-1.md
        - Sony PlayStation 2: emulacao/sony/sony-playstation-2.md
        - Sony PlayStation 3: emulacao/sony/sony-playstation-3.md
        - Sony PlayStation PSP: emulacao/sony/sony-playstation-psp.md
        - Sony PlayStation Vita: emulacao/sony/sony-playstation-vita.md
      - Emulacao - Outros: 
        - Outros Consoles: emulacao/outros/outros.md
    - Windows no Steam Deck: windows/windows.md
    - Hacks & Utilitários:
        - Hacks & Utilitários para o Steam Deck: hscks-e-utilitarios/hacks.md
        - CryoUtilities: hscks-e-utilitarios/cryoutilities.md
    - Ajuda & Dicas: ajuda/ajuda.md
  #- Game Config: game-config/index.md
  - FAQ: faq/faq.md
  - Sobre o Guia do Steam Deck: sobre.md
  - Contribua com o Guia do Steam Deck: contribua.md
  - Tags: tags.md
  - Template: template.md

